server:
  port: 8888
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://49.234.234.45:3306/blog_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: X3dOa^KP!pY75m1KzyfZA$
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    cache: false

  aop:
    auto: true
    proxy-target-class: true

  servlet:
    multipart:
      max-file-size: 1000000
      max-request-size: 1000000000



logging:
  level:
    com.wip.dao: DEBUG



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wip.model

swagger:
  show: true

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  retrunPageInfo: check

# 为了加强安全性，修改默认访问地址以及设置为登录后才可访问，可在 application.properties 文件中添加以下配置项
# 下面是在application.properties中的配置方式：
#javamelody.init-parameters.authorized-users = admin:pwd
#javamelody.init-parameters.monitoring-path = /demo/monitoring
javamelody:
  init-parameters:
    authorized-users:  admin:pwdadmin
    monitoring-path: /zky/monitoring

